version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.8.1
    steps:
      - checkout
      - run: npx prettier . --check
      # Install dependencies
      - run: npm ci
      # TODO : do we need caching for dependencies?
      # Build the application
      - run: npm run build
      # TODO: check that style.css matches compiled tailwind
      # Store the build artifacts to be used in the deploy job
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - scripts

  deploy:
    docker:
      - image: cimg/node:20.8.1
    working_directory: ~/repo
    steps:
      - checkout
      # Attach the workspace with the build artifacts
      - attach_workspace:
          at: .
      # Deploy using the script
      - run: ./scripts/deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: main
          requires:
            - build
