version: 2
jobs:
  deploy:
    docker:
      # specify the version you desire here
      - image: cimg/node:14.13.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: ./scripts/deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
