version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.8.1
    steps:
      - checkout
      - run: npx prettier . --check
      # TODO: check that style.css matches compiled tailwind
        
  
  deploy:
    docker:
      # specify the version you desire here
      - image: cimg/node:20.8.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: ./scripts/deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: main
